//Fun fact I go by my midle name.(Rousseau)

print("      R R R R R R R           o o o o o o o o o o          U               U                S           E--------------               A A                                               ")                                                                        
print("      R            R        o                    o         U               U              S             E                            A    A                      |           |          ")                                                                
print("      R            R        o                    o         U               U           S                E                           A       A                    |           |          ")                      
print("      R R R R R R R         o                    o         U               U         S                  E                          A          A                  |           |          ")                       
print("      R   R                 o                    o         U               U         S                  E---------------          A             A                |           |          ")                           
print("      R     R               o                    o         U               U           S                E                        A- - - - - - - - A              |           |          ")                                                      
print("      R       R             o                    o         U               U               S            E                       A                   A            |_ _ _ _ _ _|          ")                                                      
print("      R         R           o                    o         U               U                 S          E                      A                      A                                 ")                                               
print("      R           R           o o o o o o o o o o          U U U U U U U U U               S            E--------------       A                         A                               ")                                                   
print("                                                                                        S                                    A                            A                             ")             
print("                                                                                      S                                                                                                 ")
print("                                                                                    S                                                                                                   ")
